### ISSUE TITLE
Error(s) in loading state_dict for ResnetGenerator

### ISSUE THREAD

**Issue by yfnn** [junyanz/pytorch-CycleGAN-and-pix2pix#296] opened 2018-06-19 02:27 UTC
Today, I want to test my trained model. There are some errors not occur before.

Traceback (most recent call last):
  File "test.py", line 19, in <module>
    model.setup(opt)
  File "/home/t-fayan/vision/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 43, in setup
    self.load_networks(opt.which_epoch)
  File "/home/t-fayan/vision/pytorch-CycleGAN-and-pix2pix/models/base_model.py", line 130, in load_networks
    net.load_state_dict(state_dict)
  File "/home/t-fayan/anaconda2/envs/py27/lib/python2.7/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResnetGenerator:
        Missing key(s) in state_dict: "model.10.conv_block.6.bias", "model.10.conv_block.6.weight", "model.10.conv_block.7.running_var", "model.10.conv_block.7.running_mean", "model.11.conv_block.6.bias", "model.11.conv_block.6.weight", "model.11.conv_block.7.running_var", "model.11.conv_block.7.running_mean", "model.12.conv_block.6.bias", "model.12.conv_block.6.weight", "model.12.conv_block.7.running_var", "model.12.conv_block.7.running_mean", "model.13.conv_block.6.bias", "model.13.conv_block.6.weight", "model.13.conv_block.7.running_var", "model.13.conv_block.7.running_mean", "model.14.conv_block.6.bias", "model.14.conv_block.6.weight", "model.14.conv_block.7.running_var", "model.14.conv_block.7.running_mean", "model.15.conv_block.6.bias", "model.15.conv_block.6.weight", "model.15.conv_block.7.running_var", "model.15.conv_block.7.running_mean", "model.16.conv_block.6.bias", "model.16.conv_block.6.weight", "model.16.conv_block.7.running_var", "model.16.conv_block.7.running_mean", "model.17.conv_block.6.bias", "model.17.conv_block.6.weight", "model.17.conv_block.7.running_var", "model.17.conv_block.7.running_mean", "model.18.conv_block.6.bias", "model.18.conv_block.6.weight", "model.18.conv_block.7.running_var", "model.18.conv_block.7.running_mean".
        Unexpected key(s) in state_dict: "model.10.conv_block.5.weight", "model.10.conv_block.5.bias", "model.10.conv_block.6.running_mean", "model.10.conv_block.6.running_var", "model.11.conv_block.5.weight", "model.11.conv_block.5.bias", "model.11.conv_block.6.running_mean", "model.11.conv_block.6.running_var", "model.12.conv_block.5.weight", "model.12.conv_block.5.bias", "model.12.conv_block.6.running_mean", "model.12.conv_block.6.running_var", "model.13.conv_block.5.weight", "model.13.conv_block.5.bias", "model.13.conv_block.6.running_mean", "model.13.conv_block.6.running_var", "model.14.conv_block.5.weight", "model.14.conv_block.5.bias", "model.14.conv_block.6.running_mean", "model.14.conv_block.6.running_var", "model.15.conv_block.5.weight", "model.15.conv_block.5.bias", "model.15.conv_block.6.running_mean", "model.15.conv_block.6.running_var", "model.16.conv_block.5.weight", "model.16.conv_block.5.bias", "model.16.conv_block.6.running_mean", "model.16.conv_block.6.running_var", "model.17.conv_block.5.weight", "model.17.conv_block.5.bias", "model.17.conv_block.6.running_mean", "model.17.conv_block.6.running_var", "model.18.conv_block.5.weight", "model.18.conv_block.5.bias", "model.18.conv_block.6.running_mean", "model.18.conv_block.6.running_var".

What does it mean? Also, if I test pretrained model like horse2zebra, these errors occur too. But I didn't encounter these errors before.

**Comment by rawalkhirodkar** [comment] 2018-06-21 07:50
Facing same issue

**Comment by yfnn** [comment] 2018-06-21 09:14
I deleted the root project directory and clone this repository again. Then, it works. I don't know the reason. This is just a fast method to solve this issue for me.

**Comment by mailengm** [comment] 2018-07-12 12:41
I face the same issue. I've trained pix2pix model with the previous version of the code and tried to test it using the older and the latest commit and got the same "missing keys in state_dict" error in both.

**Comment by hao44le** [comment] 2018-07-13 05:42
Faced the same error.

<img width="1913" alt="screen shot 2018-07-12 at 10 42 24 pm" src="https://user-images.githubusercontent.com/6956728/42674507-df3d5724-8624-11e8-9deb-667a93578313.png">

**Comment by mailengm** [comment] 2018-07-13 11:34
I used the default normalization (`instancenorm`) during training and test. 
I was able to solve the problem downloading the newest version of the code and training the model again.

**Comment by pencilrocketman** [comment] 2018-07-13 11:57
I faced same error on applying a pre-train model (cyclegan).
Is `instancenorm` also related to this case?

**Comment by pencilrocketman** [comment] 2018-07-13 13:00
Sorry, I solved this problem by correct docker setting.
When I used `pytorch-nightly` instead of `pytorch, I got good results.
This is my dockerfile.(forgive my dockerfile that is dirty)
```
FROM nvidia/cuda:9.0-cudnn7-devel

RUN apt-get update && apt-get install -y \
   build-essential curl wget git cmake vim pkg-config unzip libgtk2.0-dev python3 python3-pip \
   imagemagick graphviz > /dev/null

# Miniconda3
ENV PATH /opt/conda/bin:$PATH
ENV LB_LIBRARY_PATH /opt/conda/lib:$LB_LIBRARY_PATH
RUN curl -Ls https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/install-miniconda.sh && \
   /bin/bash /tmp/install-miniconda.sh -b -p /opt/conda && \
   conda update -n base conda && \
   conda update --all -y

# Basic dependencies
RUN conda config --add channels conda-forge
RUN conda install -y readline mkl openblas numpy scipy hdf5 \
   pillow matplotlib cython pandas gensim protobuf \
   lmdb leveldb boost jupyterlab
RUN pip install pydot_ng nnpack h5py scikit-learn scikit-image hyperdash backports.ssl_match_hostname

# OpenCV
RUN conda install opencv3 -c menpo -y
RUN conda install dominate bz2file visdom

# PyTorch
RUN conda install pytorch-nightly torchvision cuda90 -c pytorch -y

# For CycleGAN and pix2pix
ADD ./vision /vision
WORKDIR /vision
RUN python3 setup.py install
WORKDIR /
```

**Comment by junyanz** [comment] 2018-07-13 17:38
@taesung89

**Comment by taesung89** [comment] 2018-07-13 23:59
The issue with `unexpected key: num_batches_tracked` should be fixed by the latest commit. 
Regarding the first error on this thread, I believe it's because PyTorch's default setting has changed. Could you get the latest pytorch and try again?

**Comment by JungJungyeji** [comment] 2018-07-16 08:22
Thank you very much. I downloaded the new version of the code and fixed the problem.

**Closed** 2018-07-24 23:13 UTC

**Comment by dovletov** [comment] 2018-11-29 16:15
I've had similar issue while trying to test CycleGAN (`--model test`) on my own dataset.
Default `--norm instance` was used for both training and testing. 
Deleting the root project directory and cloning this repository again did not help.

I've noticed that the problem is wrong keys in the `state_dict` dictionary.
E.g. model tries to load missing key "model.10.conv_block.6.weight", however there is unexpected key "model.10.conv_block.5.weight". So, I decided to fix these wrong keys. 

Based on my error message I have created two lists (missing_list and expected_list). Afterwards I've replace wrong keys with corresponding correct ones.

Example of my snippet is [here](https://gist.github.com/dovletov/8c7b742e4e19b8acf3188b6e1bc97dd1). I've inserted it after line 135 [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/0442670604839f5a5d3e1570be563a27568c16e4/models/base_model.py#L135).

**Comment by vis-opt** [comment] 2019-09-18 23:43
Another solution to this is to modify `net.load_state_dict(state_dict, strict=False)` where I added the `strict=False` option. This allows the network to load weights as long as the sizes and the number of parameters fit, even if the key-names aren't exact.

**Comment by SunLeL** [comment] 2020-05-31 08:58
I faced the same issue. But I added "--no_dropout" when I tested,  the issue was gone. As follows:
python test.py --no_dropout

**Comment by Songtingt** [comment] 2020-08-28 10:42
> I faced the same issue. But I added "--no_dropout" when I tested, the issue was gone. As follows:
> python test.py --no_dropout

Thank you @SunLeL ,it works for me!!!!

**Comment by anxingle** [comment] 2020-12-10 08:53
> I faced the same issue. But I added "--no_dropout" when I tested, the issue was gone. As follows:
> python test.py --no_dropout

Amazing!   I found when I use unet_256, it is ok. The error happens when I use resnet_6blocks.  
By the way, use --no_dropout  works for me!!!

**Comment by mr-easy** [comment] 2021-01-18 05:39
> Another solution to this is to modify `net.load_state_dict(state_dict, strict=False)` where I added the `strict=False` option. This allows the network to load weights as long as the sizes and the number of parameters fit, even if the key-names aren't exact.

Yes, this method works. One has to make the changes in `models/base_model.py` file.

**Comment by omid-ghozatlou** [comment] 2021-03-03 09:19
> Another solution to this is to modify `net.load_state_dict(state_dict, strict=False)` where I added the `strict=False` option. This allows the network to load weights as long as the sizes and the number of parameters fit, even if the key-names aren't exact.

Thank you! It is working but the results are not as good as samples saved during training. It includes much noise

**Comment by PingjunChen** [comment] 2021-06-09 19:17
@vis-opt @omid-ghozatlou I also got much noise when added `strict=False`.
